name: Build package on Push or Pull Request

on:
  push
  
jobs:
  Prepare:
    name: 'Prepare'
    uses: lulzbot3d/CuraLE_Embedded_Workflows/.github/workflows/prepare_env.yml@main
    with:
      BUILD_DOCKER_CACHE: true
    secrets: inherit

  Shellcheck:
    name: 'Test'
    needs: Prepare
    uses: lulzbot3d/CuraLE_Embedded_Workflows/.github/workflows/shellcheck.yml@main
    secrets: inherit

  Flake8:
    name: 'Test'
    needs: Prepare
    uses: lulzbot3d/Python_Quality_Control_LE/.github/workflows/flake8.yml@main
    with:
      PARENT_BRANCH: 'main'
    secrets: inherit

  MyPy:
    name: 'Test'
    needs: Prepare
    uses: lulzbot3d/Python_Quality_Control_LE/.github/workflows/mypy.yml@main
    with:
      PARENT_BRANCH: 'main'
    secrets: inherit

  PyCodeStyle:
    name: 'Test'
    needs: Prepare
    uses: lulzbot3d/Python_Quality_Control_LE/.github/workflows/pycodestyle.yml@main
    with:
      PARENT_BRANCH: 'main'
    secrets: inherit

  Vulture:
    name: 'Test'
    needs: Prepare
    uses: lulzbot3d/Python_Quality_Control_LE/.github/workflows/vulture.yml@main
    secrets: inherit

  PyTest:
    name: 'Test'
    needs: Prepare
    uses: lulzbot3d/Python_Quality_Control_LE/.github/workflows/pytest.yml@main
    secrets: inherit

  Build:
    name: 'Build'
    needs: Prepare
    uses: lulzbot3d/CuraLE_Embedded_Workflows/.github/workflows/build.yml@main
    with:
      RELEASE_VERSION: ${{ needs.Prepare.outputs.RELEASE_VERSION }}
    secrets: inherit

  Release_Package:
    name: 'Release'
    needs: [Prepare, Shellcheck, Build, Flake8, MyPy, PyCodeStyle, Vulture, PyTest]
    if: ${{ (success() && needs.Prepare.outputs.RELEASE_REPO != 'none') ||
            (failure() && needs.Build.result == 'success' && needs.Prepare.outputs.RELEASE_REPO == 'packages-dev') }}
    uses: lulzbot3d/CuraLE_Embedded_Workflows/.github/workflows/release_pkg.yml@main
    with:
      RELEASE_REPO: ${{ needs.Prepare.outputs.RELEASE_REPO }}
    secrets: inherit
